SSPAIR 1-2.A.0
0    V    L    R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    G    LG    R
0    G    LG    R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    L    R
