SSPAIR 1-2.A.1
0    V    L    R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EA    R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    L    R
1    V    L    R
2    V    EB   R
3    V    EB   .
4    V    EB   .
5    V    EB   .
6    V    EB   .
7    V    EB   .
8    V    EB   .
9    V    EB   .
10    V    EB   .
11    V    EB   .
12    G    LG    .
13    G    LG    .
14    V    EB   .
15    V    EB   .
16    V    EB   .
17    V    EB   .
18    V    EB   .
19    V    EB   .
20    V    EB   .
21    V    EB   .
22    V    EB   .
23    V    EB   .
24    V    L    .
