SSPAIR 1-2.A.99;2-3.A.99;3-4.A.99
1    V    L    .
2    V    EB   .
3    V    EB   .
4    V    EB   .
5    V    EB   .
6    V    EA    .
7    V    EB   .
8    V    EB   .
9    V    EB   .
10    V    EB   .
11    V    EB   .
12    V    L    .
13    V    L    .
14    V    EB   .
15    V    EB   .
16    V    EB   .
17    V    EB   .
18    V    EB   .
19    V    EB   .
20    V    EB   .
21    V    EB   .
22    V    EB   .
23    V    EB   .
24    G    LG    .
25    G    LG    .
26    V    EB   .
27    V    EB   .
28    V    EB   .
29    V    EB   .
30    V    EB   .
31    V    EB   .
32    V    EB   .
33    V    EB   .
34    V    EB   .
35    V    EB   R
0    V    EB   R
0    V    EB   R
36    V    L    R
0    V    L    R
0    V    EB   R
0    V    EB   R
0    V    EA    R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    L    R
