SSPAIR 1-2.A.0;1-6.P.-5;3-4.A.99
HSSTRIPLET 2,1-2;1,5-6
0    V    L    R
0    V    HA   R
0    V    HA   R
0    V    HA   R
0    V    HA   R
0    V    HA   R
0    V    HA   R
0    V    HA   R
0    V    LB    R
0    V    LB    R
0    V    LA    R
0    V    LA    R
0    V    LB    R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    G    LE    R
0    V    LA    R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    V    EB   R
0    G    LE    R
0    V    HA   R
0    V    HA   R
0    V    HA   R
0    V    HA   R
0    V    HA   R
0    V    HA   R
0    V    HA   R
0    V    HA   R
0    V    HA   R
0    V    HA   R
0    V    HA   R
0    V    HA   R
0    V    HA   R
0    V    HA   R
0    V    LB    R
1    V    LA    R
2    V    EB   R
3    V    EB   .
4    V    EB   .
5    V    EB   .
6    V    EA    .
7    V    EB   .
8    V    EB   .
9    V    EB   .
10    V    EB   .
11    V    EB   .
12    V    L    .
13    V    L    .
14    V    EB   .
15    V    EB   .
16    V    EB   .
17    V    EB   .
18    V    EB   .
19    V    EB   .
20    V    EB   .
21    V    EB   .
22    V    EB   .
23    V    EB   .
24    G    LG    .
25    G    LG    .
26    V    EB   .
27    V    EB   .
28    V    EB   .
29    V    EB   .
30    V    EB   .
31    V    EB   .
32    V    EB   .
33    V    EB   .
34    V    EB   .
35    V    EB   .
36    V    EB   .
37    V    EB   .
38    V    L    .
39    V    L    .
40    V    EB   .
41    V    EB   .
42    V    EA    .
43    V    EB   .
44    V    EB   .
45    V    EB   .
46    V    EB   .
47    V    EB   .
48    V    EB   .
49    V    L    .
